from __future__ import annotations
import numpy.typing
from ..MPI import Datatype

def from_numpy_dtype(dtype: numpy.typing.DTypeLike) -> Datatype: ...
def to_numpy_dtype(datatype: Datatype) -> numpy.dtype: ...
