# -*- shell-script -*-
MPI_VENDOR_NAME=SUNWhpc
MPI_VENDOR_VERSION=8.2.1
export MPI_DIR=/opt/$MPI_VENDOR_NAME/HPC$MPI_VENDOR_VERSION/gnu
export PATH=$MPI_DIR/bin:$PATH
export LD_LIBRARY_PATH=$MPI_DIR/lib:$LD_LIBRARY_PATH
export LDFLAGS='-m32'
