# -*- shell-script -*-
MPI_VENDOR_NAME=mpich2
MPI_VENDOR_VERSION=1.3.2
export MPI_DIR=/usr/local/$MPI_VENDOR_NAME/$MPI_VENDOR_VERSION
export PATH=$MPI_DIR/bin:$PATH
export LD_LIBRARY_PATH=$MPI_DIR/lib:$LD_LIBRARY_PATH
MPISTARTUP=mpdboot
MPISHUTDOWN=mpdallexit
