# -*- shell-script -*-
MPI_VENDOR_NAME=mpich1
MPI_VENDOR_VERSION=1.2.7
export MPI_DIR=/usr/local/$MPI_VENDOR_NAME/$MPI_VENDOR_VERSION
export PATH=$MPI_DIR/bin:$PATH
export LD_LIBRARY_PATH=$MPI_DIR/lib:$MPI_DIR/lib/shared:$LD_LIBRARY_PATH
export MPICH_USE_SHLIB=yes
