from typing import Any
from typing import Sequence

__version__: str = ...
__author__: str = ...
__credits__: str = ...

from . import MPI
__all__: list[str] = ['MPI']

class Rc:
    initialize: bool = True
    threads: bool = True
    thread_level: str = 'multiple'
    finalize: bool | None = None
    fast_reduce: bool = True
    recv_mprobe: bool = True
    errors: str = 'exception'
    def __init__(self, **kwargs: Any) -> None: ...
    def __setattr__(self, name: str, value: Any) -> None: ...
    def __call__(self, **kwargs: Any) -> None: ...
    def __repr__(self) -> str: ...

rc: Rc = ...

def get_include() -> str: ...

def get_config() -> dict[str, str]: ...

def profile(
    name: str, *,
    path: str | Sequence[str] | None = None,
) -> None: ...
