MPIABI: str | None = ...
LIBMPI: str | list[str] | None = ...
LIBMPI_PATH: str | list[str] | None = ...
LIBMPI_MODE: int | None = ...

def _register(module: str, mpiabi: str) -> None: ...
def _install_finder() -> None: ...
