import sys
from typing import Optional
if sys.version_info >= (3, 8):
    from typing import Final
else:
    from typing_extensions import Final

_Path = str
_Handle = int
_Address = int

RTLD_LAZY: Final[int] = ...
RTLD_NOW: Final[int] = ...
RTLD_GLOBAL: Final[int] = ...
RTLD_LOCAL: Final[int] = ...

RTLD_NOLOAD: Final[int] = ...
RTLD_NODELETE: Final[int] = ...
if sys.platform == 'linux':
    RTLD_DEEPBIND: Final[int] = ...
if sys.platform == 'darwin':
    RTLD_FIRST: Final[int] = ...

RTLD_DEFAULT: Final[_Handle] = ...
RTLD_NEXT: Final[_Handle] = ...
if sys.platform == 'darwin':
    RTLD_SELF: Final[_Handle] = ...
    RTLD_MAIN_ONLY: Final[_Handle] = ...

def dlopen(filename: Optional[_Path], mode: int) -> _Handle: ...
def dlclose(handle: Optional[_Handle]) -> int: ...
def dlsym(handle: Optional[_Handle], symbol: str) -> _Address: ...
def dlerror() -> Optional[str]: ...
