# https://readthedocs.org/projects/mpi4py/builds/

version: 2

formats: all

build:
  os: ubuntu-24.04
  tools:
    python: "3.14"
  jobs:
    post_install:
      - pip install --group docs

python:
  install:
    - path: .

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: true
