# https://readthedocs.org/projects/mpi4py/builds/

version: 2

formats: all

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

python:
   install:
     - path: .
     - requirements: conf/requirements-docs.txt

sphinx:
   configuration: docs/source/conf.py
   fail_on_warning: true
