# https://readthedocs.org/projects/mpi4py/builds/

version: 2

formats: all

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"

python:
  install:
    - path: .
    - requirements: conf/requirements-docs.txt

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: true
