# https://docs.astral.sh/ty/

[environment]
python-version = "3.10"
python-platform = "all"

[rules]
possibly-missing-attribute = "ignore"
possibly-missing-import = "ignore"
unresolved-attribute = "ignore"
unresolved-import = "ignore"
# unused-ignore-comment = "warn"

[src]
exclude =[
"demo",
"test",
]
