{% set build = 0 %}
{% set version = '3.0.1a0' %}
{% set mpi = (environ.get('MPI') or 'mpich') if not win else 'msmpi' %}
{% set mpi_version = {'mpich':'>=3.2', 'openmpi':'>=2.0'}.get(mpi,'') %}

package:
  name: mpi4py
  version: {{version}}

source:
# url: https://bitbucket.org/mpi4py/mpi4py/downloads/mpi4py-{{version}}.tar.gz
# git_url: https://bitbucket.org/mpi4py/mpi4py
# git_rev: master
  path: ../../../..

requirements:
  build:
    - python
    - cython >=0.22
    - {{mpi}} {{mpi_version}} # [not win]
  run:
    - python
    - {{mpi}} {{mpi_version}} # [not win]

build:
  number: {{build}}
  string: py{{py}}_{{mpi}}_{{build}}
  script: '$PYTHON  setup.py install' # [not win]
  script: '%PYTHON% setup.py install' # [win]

test:
  imports:
    - mpi4py
    - mpi4py.rc
    - mpi4py.dl # [not win]
    - mpi4py.MPI

about:
  home: https://mpi4py.bitbucket.io/
  summary: Python bindings for MPI
  description: |
    MPI for Python provides bindings of the Message Passing Interface
    (MPI) standard for the Python programming language, allowing any
    Python program to exploit multiple processors.
  doc_url: http://mpi4py.readthedocs.org/
  dev_url: https://bitbucket.org/mpi4py/mpi4py
  license: BSD 2-clause
  license_family: BSD
  license_file: LICENSE.rst

extra:
  maintainers:
   - dalcinl
