#!/bin/bash
export PATH=/opt/rh/devtoolset-2/root/usr/bin:$PATH
export ANACONDA=/opt/conda
export HYDRA_LAUNCHER=fork
export OMPI_MCA_plm=isolated
export OMPI_MCA_rmaps_base_oversubscribe=true
export OMPI_MCA_btl_base_warn_component_unused=false
export OMPI_MCA_btl_vader_single_copy_mechanism=none
source conf/ci/anaconda.sh
test-package coverage=yes $@
