trigger:
  batch: false
  branches:
    include:
      - master
      - maint
      - ci/all
      - ci/azure

jobs:

- job: Linux
  pool:
    vmImage: 'Ubuntu-22.04'
  strategy:
    matrix:
      Python36_MPICH:
        PYTHON_VERSION: '3.6'
        MPI: 'mpich'
      Python36_OpenMPI:
        PYTHON_VERSION: '3.6'
        MPI: 'openmpi'
      Python37_MPICH:
        PYTHON_VERSION: '3.7'
        MPI: 'mpich'
      Python37_OpenMPI:
        PYTHON_VERSION: '3.7'
        MPI: 'openmpi'
      Python38_MPICH:
        PYTHON_VERSION: '3.8'
        MPI: 'mpich'
      Python38_OpenMPI:
        PYTHON_VERSION: '3.8'
        MPI: 'openmpi'
      Python39_MPICH:
        PYTHON_VERSION: '3.9'
        MPI: 'mpich'
      Python39_OpenMPI:
        PYTHON_VERSION: '3.9'
        MPI: 'openmpi'
      Python310_MPICH:
        PYTHON_VERSION: '3.10'
        MPI: 'mpich'
      Python310_OpenMPI:
        PYTHON_VERSION: '3.10'
        MPI: 'openmpi'
  steps:
  - bash: echo 127.0.0.1 `hostname` | sudo tee -a /etc/hosts > /dev/null
    displayName: 'Configure hostname'
  - template: steps.yml

- job: macOS
  pool:
    vmImage: 'macOS-13'
  strategy:
    matrix:
      Python37_MPICH:
        PYTHON_VERSION: '3.7'
        MPI: 'mpich'
      Python37_OpenMPI:
        PYTHON_VERSION: '3.7'
        MPI: 'openmpi'
      Python38_MPICH:
        PYTHON_VERSION: '3.8'
        MPI: 'mpich'
      Python38_OpenMPI:
        PYTHON_VERSION: '3.8'
        MPI: 'openmpi'
      Python39_MPICH:
        PYTHON_VERSION: '3.9'
        MPI: 'mpich'
      Python39_OpenMPI:
        PYTHON_VERSION: '3.9'
        MPI: 'openmpi'
      Python310_MPICH:
        PYTHON_VERSION: '3.10'
        MPI: 'mpich'
      Python310_OpenMPI:
        PYTHON_VERSION: '3.10'
        MPI: 'openmpi'
  steps:
  - bash: echo 127.0.0.1 `hostname` | sudo tee -a /etc/hosts > /dev/null
    displayName: 'Configure hostname'
  - template: steps.yml

- job: Windows
  pool:
    vmImage: 'windows-2019'
  strategy:
    matrix:
      Python36_MSMPI:
        PYTHON_VERSION: '3.6'
        MPI: 'msmpi'
      Python37_MSMPI:
        PYTHON_VERSION: '3.7'
        MPI: 'msmpi'
      Python38_MSMPI:
        PYTHON_VERSION: '3.8'
        MPI: 'msmpi'
      Python39_MSMPI:
        PYTHON_VERSION: '3.9'
        MPI: 'msmpi'
      Python310_MSMPI:
        PYTHON_VERSION: '3.10'
        MPI: 'msmpi'
  steps:
  - template: steps.yml
  - publish: dist
    artifact: 'Windows-py$(PYTHON_VERSION)-$(MPI)'
    displayName: 'Publish package artifacts'
    condition: and(succeeded(), eq(variables['Agent.OS'], 'Windows_NT'))
