#ifndef PyMPI_CONFIG_DEINOMPI_H
#define PyMPI_CONFIG_DEINOMPI_H

#define PyMPI_API_CALL MPI_CALL

#define PyMPI_MISSING_MPI_TYPE_CREATE_F90_INTEGER 1
#define PyMPI_MISSING_MPI_TYPE_CREATE_F90_REAL 1
#define PyMPI_MISSING_MPI_TYPE_CREATE_F90_COMPLEX 1

#endif /* !PyMPI_CONFIG_DEINOMPI_H */
