#ifndef PyMPI_CONFIG_MSMPI_H
#define PyMPI_CONFIG_MSMPI_H

#define PyMPI_API_CALL MPIAPI

#define PyMPI_MISSING_MPI_TYPE_CREATE_F90_INTEGER 1
#define PyMPI_MISSING_MPI_TYPE_CREATE_F90_REAL 1
#define PyMPI_MISSING_MPI_TYPE_CREATE_F90_COMPLEX 1
#define PyMPI_MISSING_MPI_FILE_C2F 1
#define PyMPI_MISSING_MPI_FILE_F2C 1

#endif /* !PyMPI_CONFIG_MSMPI_H */
