#ifndef PyMPI_CONFIG_OPENMPI_IO_H
#define PyMPI_CONFIG_OPENMPI_IO_H

#define PyMPI_MISSING_MPI_File 1
#define PyMPI_MISSING_MPI_FILE_NULL 1
#define PyMPI_MISSING_MPI_MODE_RDONLY 1
#define PyMPI_MISSING_MPI_MODE_RDWR 1
#define PyMPI_MISSING_MPI_MODE_WRONLY 1
#define PyMPI_MISSING_MPI_MODE_CREATE 1
#define PyMPI_MISSING_MPI_MODE_EXCL 1
#define PyMPI_MISSING_MPI_MODE_DELETE_ON_CLOSE 1
#define PyMPI_MISSING_MPI_MODE_UNIQUE_OPEN 1
#define PyMPI_MISSING_MPI_MODE_APPEND 1
#define PyMPI_MISSING_MPI_MODE_SEQUENTIAL 1
#define PyMPI_MISSING_MPI_File_open 1
#define PyMPI_MISSING_MPI_File_close 1
#define PyMPI_MISSING_MPI_File_delete 1
#define PyMPI_MISSING_MPI_File_set_size 1
#define PyMPI_MISSING_MPI_File_preallocate 1
#define PyMPI_MISSING_MPI_File_get_size 1
#define PyMPI_MISSING_MPI_File_get_group 1
#define PyMPI_MISSING_MPI_File_get_amode 1
#define PyMPI_MISSING_MPI_File_set_info 1
#define PyMPI_MISSING_MPI_File_get_info 1
#define PyMPI_MISSING_MPI_File_get_view 1
#define PyMPI_MISSING_MPI_File_set_view 1
#define PyMPI_MISSING_MPI_File_read_at 1
#define PyMPI_MISSING_MPI_File_read_at_all 1
#define PyMPI_MISSING_MPI_File_write_at 1
#define PyMPI_MISSING_MPI_File_write_at_all 1
#define PyMPI_MISSING_MPI_File_iread_at 1
#define PyMPI_MISSING_MPI_File_iwrite_at 1
#define PyMPI_MISSING_MPI_SEEK_SET 1
#define PyMPI_MISSING_MPI_SEEK_CUR 1
#define PyMPI_MISSING_MPI_SEEK_END 1
#define PyMPI_MISSING_MPI_DISPLACEMENT_CURRENT 1
#define PyMPI_MISSING_MPI_File_seek 1
#define PyMPI_MISSING_MPI_File_get_position 1
#define PyMPI_MISSING_MPI_File_get_byte_offset 1
#define PyMPI_MISSING_MPI_File_read 1
#define PyMPI_MISSING_MPI_File_read_all 1
#define PyMPI_MISSING_MPI_File_write 1
#define PyMPI_MISSING_MPI_File_write_all 1
#define PyMPI_MISSING_MPI_File_iread 1
#define PyMPI_MISSING_MPI_File_iwrite 1
#define PyMPI_MISSING_MPI_File_read_shared 1
#define PyMPI_MISSING_MPI_File_write_shared 1
#define PyMPI_MISSING_MPI_File_iread_shared 1
#define PyMPI_MISSING_MPI_File_iwrite_shared 1
#define PyMPI_MISSING_MPI_File_read_ordered 1
#define PyMPI_MISSING_MPI_File_write_ordered 1
#define PyMPI_MISSING_MPI_File_seek_shared 1
#define PyMPI_MISSING_MPI_File_get_position_shared 1
#define PyMPI_MISSING_MPI_File_read_at_all_begin 1
#define PyMPI_MISSING_MPI_File_read_at_all_end 1
#define PyMPI_MISSING_MPI_File_write_at_all_begin 1
#define PyMPI_MISSING_MPI_File_write_at_all_end 1
#define PyMPI_MISSING_MPI_File_read_all_begin 1
#define PyMPI_MISSING_MPI_File_read_all_end 1
#define PyMPI_MISSING_MPI_File_write_all_begin 1
#define PyMPI_MISSING_MPI_File_write_all_end 1
#define PyMPI_MISSING_MPI_File_read_ordered_begin 1
#define PyMPI_MISSING_MPI_File_read_ordered_end 1
#define PyMPI_MISSING_MPI_File_write_ordered_begin 1
#define PyMPI_MISSING_MPI_File_write_ordered_end 1
#define PyMPI_MISSING_MPI_File_get_type_extent 1
#define PyMPI_MISSING_MPI_File_set_atomicity 1
#define PyMPI_MISSING_MPI_File_get_atomicity 1
#define PyMPI_MISSING_MPI_File_sync 1
#define PyMPI_MISSING_MPI_File_get_errhandler 1
#define PyMPI_MISSING_MPI_File_set_errhandler 1
#define PyMPI_MISSING_MPI_File_errhandler_fn 1
#define PyMPI_MISSING_MPI_File_errhandler_function 1
#define PyMPI_MISSING_MPI_File_create_errhandler 1
#define PyMPI_MISSING_MPI_File_call_errhandler 1

#define PyMPI_MISSING_MPI_Datarep_conversion_function 1
#define PyMPI_MISSING_MPI_Datarep_extent_function 1
#define PyMPI_MISSING_MPI_CONVERSION_FN_NULL 1
#define PyMPI_MISSING_MPI_MAX_DATAREP_STRING 1
#define PyMPI_MISSING_MPI_Register_datarep 1

#define PyMPI_MISSING_MPI_File_c2f 1
#define PyMPI_MISSING_MPI_File_f2c 1

#if !defined(MPI_ERR_FILE)
#define PyMPI_MISSING_MPI_ERR_FILE 1
#define PyMPI_MISSING_MPI_ERR_NOT_SAME 1
#define PyMPI_MISSING_MPI_ERR_BAD_FILE 1
#define PyMPI_MISSING_MPI_ERR_NO_SUCH_FILE 1
#define PyMPI_MISSING_MPI_ERR_FILE_EXISTS 1
#define PyMPI_MISSING_MPI_ERR_FILE_IN_USE 1
#define PyMPI_MISSING_MPI_ERR_AMODE 1
#define PyMPI_MISSING_MPI_ERR_ACCESS 1
#define PyMPI_MISSING_MPI_ERR_READ_ONLY 1
#define PyMPI_MISSING_MPI_ERR_NO_SPACE 1
#define PyMPI_MISSING_MPI_ERR_QUOTA 1
#define PyMPI_MISSING_MPI_ERR_UNSUPPORTED_DATAREP 1
#define PyMPI_MISSING_MPI_ERR_UNSUPPORTED_OPERATION 1
#define PyMPI_MISSING_MPI_ERR_CONVERSION 1
#define PyMPI_MISSING_MPI_ERR_DUP_DATAREP 1
#define PyMPI_MISSING_MPI_ERR_IO 1
#endif

#endif /* !PyMPI_CONFIG_OPENMPI_IO_H */
