#ifndef PyMPI_CONFIG_OPENMPI_H
#define PyMPI_CONFIG_OPENMPI_H

#if !OMPI_HAVE_FORTRAN_LOGICAL1
#define PyMPI_MISSING_MPI_LOGICAL1 1
#endif
#if !OMPI_HAVE_FORTRAN_LOGICAL2
#define PyMPI_MISSING_MPI_LOGICAL2 1
#endif
#if !OMPI_HAVE_FORTRAN_LOGICAL4
#define PyMPI_MISSING_MPI_LOGICAL4 1
#endif
#if !OMPI_HAVE_FORTRAN_LOGICAL8
#define PyMPI_MISSING_MPI_LOGICAL8 1
#endif

#if !OMPI_HAVE_FORTRAN_INTEGER1
#define PyMPI_MISSING_MPI_INTEGER1 1
#endif
#if !OMPI_HAVE_FORTRAN_INTEGER2
#define PyMPI_MISSING_MPI_INTEGER2 1
#endif
#if !OMPI_HAVE_FORTRAN_INTEGER4
#define PyMPI_MISSING_MPI_INTEGER4 1
#endif
#if !OMPI_HAVE_FORTRAN_INTEGER8
#define PyMPI_MISSING_MPI_INTEGER8 1
#endif
#if !OMPI_HAVE_FORTRAN_INTEGER16
#define PyMPI_MISSING_MPI_INTEGER16 1
#endif

#if !OMPI_HAVE_FORTRAN_REAL2
#define PyMPI_MISSING_MPI_REAL2
#define PyMPI_MISSING_MPI_COMPLEX4 1
#endif
#if !OMPI_HAVE_FORTRAN_REAL4
#define PyMPI_MISSING_MPI_REAL4 1
#define PyMPI_MISSING_MPI_COMPLEX8 1
#endif
#if !OMPI_HAVE_FORTRAN_REAL8
#define PyMPI_MISSING_MPI_REAL8 1
#define PyMPI_MISSING_MPI_COMPLEX16 1
#endif
#if !OMPI_HAVE_FORTRAN_REAL16
#define PyMPI_MISSING_MPI_REAL16 1
#define PyMPI_MISSING_MPI_COMPLEX32 1
#endif

#if MPI_VERSION==2 && MPI_SUBVERSION<2
#define PyMPI_MISSING_MPI_COMPLEX4 1
#endif

#endif /* !PyMPI_CONFIG_OPENMPI_H */
