#if defined(MPI_VERSION)
#if (MPI_VERSION >= 5)

/*
#define PyMPI_HAVE_MPI_LOGICAL1 1
#define PyMPI_HAVE_MPI_LOGICAL2 1
#define PyMPI_HAVE_MPI_LOGICAL4 1
#define PyMPI_HAVE_MPI_LOGICAL8 1
#define PyMPI_HAVE_MPI_LOGICAL16 1
*/

#endif
#endif
