.PHONY: default

default:
	${MAKE} -C compute-pi
	${MAKE} -C nxtval
	${MAKE} -C mandelbrot
	${MAKE} -C spawning

	${MAKE} -C cython
	${MAKE} -C f2py
	${MAKE} -C swig
	${MAKE} -C embedding

	${MAKE} -C mpi-ref-v1
	${MAKE} -C init-fini
	${MAKE} -C threads
