package:
  name: openmpi
  version: 2.0.1

about:
  home: http://www.open-mpi.org/
  summary: 'Open MPI: A high performance message passing library'
  license: 'BSD (https://www.open-mpi.org/community/license.php)'

requirements:
  conflicts:
    - mpich
    - mpich2

source:
  fn: openmpi-2.0.1.tar.bz2
  url: http://www.open-mpi.org/software/ompi/v2.0/downloads/openmpi-2.0.1.tar.bz2
  md5: 6f78155bd7203039d2448390f3b51c96

build:
  number: 0
  features:
    - openmpi
  track_features:
    - openmpi
  skip: true # [win]
  binary_relocation: true
  detect_binary_files_with_prefix: true

test:
  files:
    - test/helloworld.c
    - test/helloworld.cxx
  commands:
    - command -v ompi_info
    - ompi_info
    - command -v mpiexec
    - mpiexec -n 4 hostname
    - command -v mpicc
    - mpicc -show
    - mpicc test/helloworld.c -o helloworld_c
    - export DYLD_LIBRARY_PATH=$PREFIX/lib # [osx]
    - mpiexec -n 4 ./helloworld_c
