name: ci-cover

on:
  workflow_call:
    inputs:
      py:
        description: 'Python version'
        required: false
        default: 3
        type: string
  workflow_dispatch:
    inputs:
      py:
        description: 'Python version'
        required: true
        default: 3
        type: string

permissions:
  contents: read

jobs:

  cover:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        mpi:
          - mpich
        py:
          - ${{ github.event.inputs.py || 3 }}
    defaults:
      run:
        shell: bash -el {0}

    steps:

    - uses: actions/checkout@v3

    - uses: conda-incubator/setup-miniconda@v2
      with:
        miniforge-variant: Mambaforge
        miniforge-version: latest
        channel-priority: strict
        use-mamba: true
        python-version: ${{ matrix.py }}
        add-pip-as-python-dependency: true
    - run: mamba info

    - run: mamba install
             ${{ matrix.mpi }}
             ${{ matrix.mpi }}-mpicc
             cython
             coverage
             numpy
    - run: mamba list

    - run: conf/cycoverage.sh
    - run: conf/cythonize.sh

    - run: python -m pip install .
      env:
        CFLAGS: "-O0 -DCYTHON_TRACE_NOGIL=1"
        PIP_VERBOSE: "3"
        PIP_NO_CACHE_DIR: "true"
        PIP_NO_BUILD_ISOLATION: "false"  # pypa/pip#5735
        PIP_DISABLE_PIP_VERSION_CHECK: "true"

    - name: Set PYTHONPATH=$PWD
      run:  echo "PYTHONPATH=${PWD}" >> $GITHUB_ENV

    - name: Run coverage
      run:  bash -x ./test/coverage.sh

    - name: Prepare coverage data
      run:  mv .coverage .coverage.${TAG}
      env:
        TAG: ${{ runner.os }}.${{ matrix.mpi }}.py${{ matrix.py }}

    - name: Upload coverage data
      uses: actions/upload-artifact@v3
      with:
        name: coverage-data
        path: ".coverage.*"
        if-no-files-found: ignore

  report:
    runs-on: ubuntu-latest
    needs: cover
    if: always()

    steps:

    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ github.event.inputs.py || 3 }}

    - run: python -m pip install cython coverage
    - run: conf/cycoverage.sh
    - run: conf/cythonize.sh

    - name: Download coverage data
      uses: actions/download-artifact@v3
      with:
        name: coverage-data

    - name: Report coverage
      run: |
        python -m coverage combine
        python -m coverage html
        python -m coverage xml
        python -m coverage report --format=markdown >> $GITHUB_STEP_SUMMARY
        python -m coverage report --fail-under=100

    - name: Upload HTML report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-html
        path: htmlcov
      if: failure()
